29.03.21 homework_git_27_28 done
EfimovEO/HOMEWORK-EP pull request #1
Opened 2021-03-29 16:45 UTC by EfimovEO

github раньше не пользовался, надеюсь действую правильно.

2021-03-29 20:52 UTC, SagurovA93 requested changes
Good work! Could you review my comments in discussions and answer the questions/leave your comments, please. 

As additional questions I would like to ask the following questions:
1. What will happen when your local GitLab docker container will stop? Will it keep configurations and code?
2. How to setup root password before Gitlabb starts?

2021-03-29 20:52 UTC, SagurovA93 commented on Homework_git_27-28_EfimovEO.txt
> +[admin@andromeda lection_git_hw]$ git add temp_file && git commit ./temp_file -m "p.6 of hw"
Use `git commit` directly to the file if you need to commit it directly.

This construction: `git add temp_file && git commit ./temp_file` should be replaced by `git commit`.

2021-03-29 20:52 UTC, SagurovA93 commented on Homework_git_27-28_EfimovEO.txt
> +  11. Allow anyone do anything in branches like "feature-*"
According to this screenshot 
![image](https://user-images.githubusercontent.com/22913295/112898275-4ab3a900-90e9-11eb-92a1-bdc104e4f449.png)


I have a question for you:
Can Maintainer push to the master branch with `push` and `push -f`?

2021-03-30 10:28 UTC, EfimovEO commented on Homework_git_27-28_EfimovEO.txt
> +[admin@andromeda lection_git_hw]$ git add temp_file && git commit ./temp_file -m "p.6 of hw"
ok. i will do so next time

2021-03-30 10:29 UTC, EfimovEO commented on Homework_git_27-28_EfimovEO.txt
> +  11. Allow anyone do anything in branches like "feature-*"
i think he can't

2021-03-30 11:03 UTC, EfimovEO commented
> Good work! Could you review my comments in discussions and answer the questions/leave your comments, please.
> 
> As additional questions I would like to ask the following questions:
> 
>     1. What will happen when your local GitLab docker container will stop? Will it keep configurations and code?
> 
>     2. How to setup root password before Gitlabb starts?

1. When local Gitlab docker container will stop it will keep configurantions and code, because Gitlab writes them to the VOLUMES, which were created when container has started.

2. I didn't try but here is what i've found:
 define GITLAB_OMNIBUS_CONFIG as an environment variable in docker-compose file, like:
     environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'adminadmin'

2021-03-31 17:06 UTC, SagurovA93 commented on Homework_git_27-28_EfimovEO.txt
> +  11. Allow anyone do anything in branches like "feature-*"
Could you check it? :)

2021-03-31 17:06 UTC, SagurovA93 approved these changes

2021-03-31 17:07 UTC, SagurovA93 commented
Good to go

2021-04-05 16:32 UTC, merged